replicas: 1

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 40Gi

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

esJavaOpts: "-Xms512m -Xmx512m"

persistence:
  enabled: true
  storageClass: standard-rwo
  size: 20Gi
      
